#!/usr/bin/env python
#-*-coding:utf-8-*-
# @File:data_process
# @Author: Michael.liu
# @Date:2020/6/19 20:06
# @Desc: this code is ....
import pandas as pd
import numpy as np

def data_preprocess():
    print("Loading data...")
